# Generated by Django 5.1.15 on 2026-05-22 15:35

import apps.tenants.managers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('revenue_drop', 'Queda de faturamento'), ('revenue_surge', 'Pico de faturamento'), ('expense_surge', 'Despesa fora do padrão'), ('top_customer', 'Cliente que mais comprou'), ('top_product', 'Produto mais vendido'), ('inactive_customer', 'Cliente inativo'), ('overdue_high', 'Inadimplência alta'), ('cash_negative', 'Caixa negativo'), ('ticket_drop', 'Ticket médio caindo'), ('seasonality', 'Sazonalidade detectada')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Informação'), ('success', 'Positivo'), ('warning', 'Atenção'), ('critical', 'Crítico')], db_index=True, default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('narrative', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('generated_by', models.CharField(default='rules', max_length=32)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='insights_in_tenant__9644d3_idx'), models.Index(fields=['tenant', 'kind', '-created_at'], name='insights_in_tenant__1989c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind', 'period_start', 'period_end'), name='uniq_insight_per_period')],
            },
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
    ]
