# Generated by Django 5.1.15 on 2026-05-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='kind',
            field=models.CharField(choices=[('revenue_drop', 'Queda de faturamento'), ('revenue_surge', 'Pico de faturamento'), ('expense_surge', 'Despesa fora do padrão'), ('top_customer', 'Cliente que mais comprou'), ('top_product', 'Produto mais vendido'), ('inactive_customer', 'Cliente inativo'), ('overdue_high', 'Inadimplência alta'), ('cash_negative', 'Caixa negativo'), ('ticket_drop', 'Ticket médio caindo'), ('seasonality', 'Sazonalidade detectada'), ('top_expense_category', 'Categoria de maior despesa'), ('top_revenue_category', 'Categoria de maior receita'), ('upcoming_payables', 'Compromissos próximos'), ('supplier_concentration', 'Concentração em fornecedor'), ('cash_in_trend', 'Tendência de recebimentos')], db_index=True, max_length=32),
        ),
    ]
