# Generated by Django 5.1.15 on 2026-05-22 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Cadastro'), ('password_change', 'Troca de senha'), ('contaazul_connect', 'Conexão Conta Azul'), ('contaazul_disconnect', 'Desconexão Conta Azul'), ('credentials_updated', 'Credenciais atualizadas'), ('sync_triggered', 'Sincronização disparada'), ('subscription_checkout', 'Checkout iniciado'), ('subscription_canceled', 'Assinatura cancelada'), ('subscription_reactivated', 'Assinatura reativada'), ('data_export', 'Exportação de dados (LGPD)'), ('data_delete', 'Exclusão de dados (LGPD)'), ('admin_access', 'Acesso admin SaaS')], db_index=True, max_length=64)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='security_au_tenant__fbf84e_idx'), models.Index(fields=['actor', '-created_at'], name='security_au_actor_i_deb793_idx'), models.Index(fields=['action', '-created_at'], name='security_au_action_3e8501_idx')],
            },
        ),
    ]
