# Generated by Django 5.1.15 on 2026-05-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Cadastro"),
                    ("password_change", "Troca de senha"),
                    ("password_reset_request", "Solicitação de redefinição de senha"),
                    ("password_reset_confirm", "Senha redefinida via e-mail"),
                    ("contaazul_connect", "Conexão Conta Azul"),
                    ("contaazul_disconnect", "Desconexão Conta Azul"),
                    ("credentials_updated", "Credenciais atualizadas"),
                    ("sync_triggered", "Sincronização disparada"),
                    ("subscription_checkout", "Checkout iniciado"),
                    ("subscription_canceled", "Assinatura cancelada"),
                    ("subscription_reactivated", "Assinatura reativada"),
                    ("data_export", "Exportação de dados (LGPD)"),
                    ("data_delete", "Exclusão de dados (LGPD)"),
                    ("admin_access", "Acesso admin SaaS"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
