# Generated by Django 5.1.15 on 2026-05-22 19:10

import apps.tenants.managers
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('revenue', 'Faturamento'), ('net_profit', 'Lucro líquido'), ('num_sales', 'Nº de vendas'), ('avg_ticket', 'Ticket médio')], max_length=20)),
                ('period', models.CharField(choices=[('month', 'Mensal'), ('quarter', 'Trimestral'), ('year', 'Anual')], default='month', max_length=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('starts_on', models.DateField(db_index=True, default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='goals_goal_tenant__4c5f64_idx'), models.Index(fields=['tenant', 'kind'], name='goals_goal_tenant__d9d633_idx')],
            },
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
    ]
