# Generated by Django 5.1.15 on 2026-05-14 20:03

import apps.tenants.managers
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('revenue', 'Receita'), ('expense', 'Despesa'), ('other', 'Outro')], default='other', max_length=16)),
                ('parent_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at_external', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('direction', models.CharField(choices=[('receivable', 'A receber'), ('payable', 'A pagar')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago/Recebido'), ('overdue', 'Atrasado'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='sync.category')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='sync.customer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('closed', 'Fechada'), ('canceled', 'Cancelada')], default='open', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sync.customer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='sync.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sync.salesperson'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched', models.IntegerField(default=0)),
                ('upserted', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('cursor', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('customers', 'Customers (pessoas)'), ('sales', 'Sales'), ('products', 'Products'), ('financial_receivables', 'Contas a receber'), ('financial_payables', 'Contas a pagar'), ('categories', 'Categorias'), ('salespeople', 'Vendedores')], db_index=True, max_length=32)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('schema_version', models.SmallIntegerField(default=1)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payloads', to='sync.synclog')),
            ],
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_category_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'name'], name='sync_custom_tenant__8568e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_customer_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['tenant', 'direction', 'due_date'], name='sync_financ_tenant__b1e6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='sync_financ_tenant__2e198e_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_financial_entry_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'name'], name='sync_produc_tenant__97b9ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_product_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['tenant', 'sale'], name='sync_saleit_tenant__ca1d72_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesperson',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_salesperson_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'issued_at'], name='sync_sale_tenant__6cf393_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'status'], name='sync_sale_tenant__49172c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='uniq_sale_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['tenant', '-started_at'], name='sync_synclo_tenant__970fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['tenant', 'resource', '-started_at'], name='sync_synclo_tenant__9b8b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawpayload',
            index=models.Index(fields=['tenant', 'resource', 'external_id'], name='sync_rawpay_tenant__e8ff4b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawpayload',
            index=models.Index(fields=['tenant', 'resource', 'fetched_at'], name='sync_rawpay_tenant__bde7ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawpayload',
            constraint=models.UniqueConstraint(fields=('tenant', 'resource', 'external_id', 'fetched_at'), name='uniq_bronze_payload'),
        ),
    ]
