# Generated by Django 5.1.15 on 2026-05-23 01:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
    ]
