# Generated by Django 5.1.15 on 2026-05-23 21:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(choices=[('month', 'Mensal'), ('year', 'Anual')], default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('starter', 'Starter (legacy)'), ('growth', 'Growth (legacy)'), ('business', 'Business (legacy)'), ('monthly', 'Mensal'), ('annual', 'Anual')], max_length=32, unique=True),
        ),
    ]
