# Generated by Django 5.1.15 on 2026-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_simplify_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="billing_interval_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="plan",
            name="billing_interval",
            field=models.CharField(
                choices=[("month", "Mês"), ("year", "Ano")], default="month", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="code",
            field=models.CharField(
                choices=[
                    ("starter", "Starter (legacy)"),
                    ("growth", "Growth (legacy)"),
                    ("business", "Business (legacy)"),
                    ("monthly", "Mensal"),
                    ("semestral", "Semestral"),
                    ("annual", "Anual"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
