# Generated by Django 5.1.15 on 2026-05-14 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAzulConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('error', 'Erro'), ('revoked', 'Revogado')], default='disconnected', max_length=16)),
                ('access_token_enc', models.TextField(blank=True, default='')),
                ('refresh_token_enc', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contaazul_connection', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='integration_status_782c29_idx'), models.Index(fields=['expires_at'], name='integration_expires_ab6e22_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=64, unique=True)),
                ('initiated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contaazul_oauth_states', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='integration_created_54f9e7_idx')],
            },
        ),
    ]
