# Generated by Django 5.1.15 on 2026-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaazulconnection',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contaazulconnection',
            name='client_secret_enc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
