# Generated by Django 5.1.15 on 2026-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_contaazulconnection_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaazulconnection',
            name='auth_url_override',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contaazulconnection',
            name='redirect_uri_override',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
