# Generated by Django 5.1.15 on 2026-05-22 19:10

import apps.tenants.managers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('dashboard', models.CharField(choices=[('executive', 'Executivo'), ('financial', 'Financeiro'), ('commercial', 'Comercial')], max_length=20)),
                ('preset', models.CharField(blank=True, default='last_12m', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='reports_sha_tenant__c32d20_idx')],
            },
            managers=[
                ('objects', apps.tenants.managers.TenantScopedManager()),
                ('unsafe_objects', apps.tenants.managers.UnscopedManager()),
            ],
        ),
    ]
